name: Run Maestro Tests

on:
  push:
    branches:
      - testCase
  pull_request:
    branches:
      - main

jobs:
  maestro-tests:
    runs-on: macos-latest  # Use macOS instead of Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java (Required for Maestro)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Verify Java Installation
        run: java -version

      - name: Install Maestro and iOS Dependencies
        run: |
          brew install mobile-dev-inc/tap/maestro
          echo 'export PATH="$HOME/.maestro/bin:$PATH"' >> $HOME/.zshrc
          export PATH="$HOME/.maestro/bin:$PATH"

      - name: Verify Maestro Installation
        run: |
          export PATH="$HOME/.maestro/bin:$PATH"
          maestro --version

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 14" || echo "Simulator already booted"
          xcrun simctl list devices
      - name: Run All Maestro E2E Tests
        run: |
          for test in e2e/*.yaml; do
            echo "Running test: $test"
            maestro test "$test" --format junit --output e2e/results-$(basename "$test" .yaml).xml || exit 1
          done

      # - name: Run Maestro Tests
      #   run: |
      #     export PATH="$HOME/.maestro/bin:$PATH"
      #     maestro test test_cases/login.yaml --device "iPhone 14"

