name: E2E Tests with Maestro (iOS)

on:
  push:
    branches:
      - testCase
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    name: Run Maestro E2E Tests (iOS)
    runs-on: macos-latest # Required for iOS simulator

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive # Add if using submodules
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Debug Repository Structure
        run: ls -R

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Verify Maestro Installation
        run: |
          maestro --version
          which maestro

      - name: Debug iOS Workspace
        run: |
          cd ios
          ls -la
          xcodebuild -list -workspace Burst.xcworkspace
          cd ..

      - name: Build iOS App for Testing
        run: |
          cd ios
          xcodebuild -workspace Burst.xcworkspace \
                     -scheme Burst \
                     -configuration Debug \
                     -sdk iphonesimulator \
                     -derivedDataPath ~/Library/Developer/Xcode/DerivedData
          cd ..

      - name: Debug Maestro Test Files
        run: |
          ls -la e2e

      - name: Run All Maestro E2E Tests
        run: |
          for test in e2e/*.yaml; do
            echo "Running test: $test"
            maestro test "$test" --format junit --output e2e/results-$(basename "$test" .yaml).xml || exit 1
          done

      - name: Upload Test Results (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: maestro-test-results
          path: e2e/*.xml